Somesh-Debnath/Hacktober_2022_Programs

- Cpp/SieveOfEratosthenes.cpp
help to find prime number in a range
> created SieveOfEratosthenes.cpp

- Cpp/linkedlist/add2num.cpp
- Cpp/linkedlist/dummy.txt
- Cpp/linkedlist/intersectlist.cpp
- Cpp/linkedlist/listCycle.cpp
- Cpp/linkedlist/merge2list.cpp
- Cpp/linkedlist/middlelist.cpp
- Cpp/linkedlist/removefromend.cpp
- Cpp/linkedlist/reverselist.cpp
All basic linked list questions
> Linked List questions

- Cpp/dijkastra.cpp
> Added Dijkastra's Algorithm

- Cpp/Trap.cpp
https://leetcode.com/problems/trapping-rain-water/
> trapping rain water problem

- Cpp/implementationTree.cpp
I have added tree implimentation program. Thank you
> Added tree implimentation program

- tree_queries.cpp
I have solved this problem,please do consider merging it.
thanking you.
> tree_queries.cpp

- C/compare two linked lists.c
I have added compare two linked lists.c
> Create compare two linked lists.c

- javascript/Search_A_2D_Matrix
Leetcode Problem Link : https://leetcode.com/problems/search-a-2d-matrix/
> Solution : 74. Search a 2D Matrix (Leetcode)

- C/inversion count.c
> Create inversion count.c

- counting_sort.cpp
Please consider my pr and also tag this under hacktoberfest
> Counting Sort

- Cpp/minimumnotation_codeforces.cpp
https://codeforces.com/contest/1730/problem/C .  This is the problem link
thank you for reading my pull request please merge my code into your repository.
> a new file minimum notation codeforces problem added

- Cpp/Removing_smallest_multiples.cpp
Thank you for reading my pull request.
Added the solution for : https://codeforces.com/contest/1734/problem/C
> added a new file removing smallest multiple codeforces

- C/Breadth first search.c
> Create Breadth first search.c

- Cpp/Circular Queue Implementation.cpp
Added Circular Queue Implementation.cpp
> Create Circular Queue Implementation.cpp

- C/Priority Queue using the binary max heap.c
Added Priority Queue using the binary max heap.c
> Create Priority Queue using the binary max heap.c

- Cpp/Implement Counting Sort.cpp
Added Implement Counting Sort.cpp
> Create Implement Counting Sort.cpp

- C/Implement Hash Table.c
> Create Implement Hash Table.c

- C/Linked list implementation.c
Added Linked list implementation.c
> Create Linked list implementation.c

- C/Dijkstra's Algorithm.c
> Create Dijkstra's Algorithm.c

- C/Adjacency Matrix representation.c
- C/Ford-Fulkerson Algorithm.c
Added Adjacency Matrix representation.c
> Adjacency Matrix representation.c

- C/Adjacency Matrix representation.c
- C/Ford-Fulkerson Algorithm.c
Added Ford-Fulkerson Algorithm.c
> Create Ford-Fulkerson Algorithm.c

- Python/Shell sort.py
> Create Shell sort.py

- Cpp/Jump Game II.cpp
> Added Jump Game II

- C/Swapping_without_third_variable.c
Hi i have created a program that swaps the values of 2 variable with one command without a need for a third variable,
I am new to contributing and open source in general , so if i broke any rules i am sorry.
Thanks for looking through my code.😀 and i hope you will merge this under hacktoberfest.
> simple program to swap value of 2  variables.

- Graph/Adjacency_matrix
- Graph/DisjointSetUnion.cpp
- Graph/Find_if_a_cycle_exists_in_a_graph.cpp
- Graph/KosarajuConnectedComponents.cpp
- Graph/MotherVertexKosaraju.cpp
- Graph/PetersenGraph.cpp
- Graph/adjacencylist.cpp
- Graph/articulationPoints.cpp
- Graph/bellmanFord.cpp
- Graph/bfs.cpp
- Graph/bipartite_detection.cpp
- Graph/bridge.cpp
- Graph/connected_components.cpp
- Graph/cycle_detection_undirected.cpp
- Graph/detectCycle.cpp
- Graph/detectCycleIn_Directed_graph.cpp
- Graph/dfs.cpp
- Graph/dijkstra.cpp
- Graph/eulerPath.cpp
- Graph/flood_fill.cpp
- Graph/floydWarshall.cpp
- Graph/getPath.cpp
- Graph/graph.cpp
- Graph/krushkalalgousingdsu.cpp
- Graph/krushkalnotes.md
- Graph/mst.cpp
- Graph/prims.cpp
- Graph/scc.cpp
- Graph/topSort.cpp
- Graph/tsp.cpp
> Added Graph

- C/Bucket Sort Algorithm.c
> Create Bucket Sort Algorithm.c

- Star_Pattern.cpp
The above cpp file will print the star pattern.
> Star Pattern.cpp

- Python/Temp_converter.py
Please merge this under hactoberfest 2022 .Thnx.
> Adding a program to convert temperatures.

- binarysearch.cpp
> binary_search_program

- R/bubble_sort.r
> bubble_sort

- Cpp/ela_sorting_books
Thank you for reading my pull request.
Please merge my PR.
> Added a codeforces question solution

- Cpp/search_2d_matrix.cpp
Write an efficient algorithm that searches for a value target in an m x n integer matrix matrix. This matrix has the following properties:
Integers in each row are sorted from left to right. The first integer of each row is greater than the last integer of the previous row.
> Created search_2d_matrix.cpp

- Cpp/LRU_Cache.cpp
Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.
> Created LRU_Cache.cpp

- C/DFS_Array.c
> DFS array implementation
